/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lap7;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Diagram extends javax.swing.JFrame {

    /**
     * Creates new form Diagram
     */
    public Diagram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "xóa", "rectangle", "square", "cirle", "triangle", "hexagon" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextPane1.setText("Tên hình");
        jScrollPane3.setViewportView(jTextPane1);

        jTextPane2.setText("hiển thị");
        jScrollPane4.setViewportView(jTextPane2);

        jTextPane3.setText("Màu sắc");
        jScrollPane5.setViewportView(jTextPane3);

        jTextPane4.setText("Tọa độ tâm (cirle, rectangle,square)");
        jScrollPane6.setViewportView(jTextPane4);

        jTextPane5.setText("Hoành độ đỉnh (cách nhau bởi dấu \"cách\")");
        jScrollPane7.setViewportView(jTextPane5);

        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có", "Không" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "đen", "xanh dương", "xanh lá", "vàng", "hồng" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextPane6.setText("Tung độ đỉnh (cách nhau bởi dấu \"cách\")");
        jScrollPane8.setViewportView(jTextPane6);

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton3.setText("thay đổi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("xóa hình giống nhau");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addGap(5, 5, 5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, 114, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6)
                            .addComponent(jTextField4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jTextField5)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList<Layer> layer = new ArrayList<Layer>();
    DefaultListModel<String> listModel = new DefaultListModel<>();
    DefaultListModel<String> listMode2 = new DefaultListModel<>();
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("xóa")){
            if(jList1.getSelectedIndex()<0) JOptionPane.showMessageDialog(rootPane, "bạn cần chọn layer");
            else if(jList2.getSelectedIndex()<0) JOptionPane.showMessageDialog(rootPane, "bạn cần chọn shape");
            else {
                int i = jList1.getSelectedIndex();
                int j = jList2.getSelectedIndex();
                listMode2.remove(j);
                layer.get(i).shapes.remove(j);
                jList2.setModel(listMode2);
            }
        }
        else{
        if(jList1.getSelectedIndex()<0) JOptionPane.showMessageDialog(rootPane, "bạn cần chọn layer");
        else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("cirle")){
            Cirle a = new Cirle();
            a.setName(layer.get(jList1.getSelectedIndex()).shapes.size()+" cirle");
            if(jList1.getSelectedIndex()<0) JOptionPane.showMessageDialog(rootPane, "bạn cần chọn layer");
            else {
                layer.get(jList1.getSelectedIndex()).shapes.add(a);
                listMode2.addElement(a.getName());
                jList2.setModel(listMode2);
            }
        }
        else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("rectangle")){
            Rectangle a = new Rectangle();
            a.setName(layer.get(jList1.getSelectedIndex()).shapes.size()+" rectangle");
            if(jList1.getSelectedIndex()<0) JOptionPane.showMessageDialog(rootPane, "bạn cần chọn layer");
            else {
                layer.get(jList1.getSelectedIndex()).shapes.add(a);
                listMode2.addElement(a.getName());
                jList2.setModel(listMode2);
            }
        }
        else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("hexagon")){
            Hexagon a = new Hexagon();
            a.setName(layer.get(jList1.getSelectedIndex()).shapes.size()+" hexagon");
            if(jList1.getSelectedIndex()<0) JOptionPane.showMessageDialog(rootPane, "bạn cần chọn layer");
            else {
                layer.get(jList1.getSelectedIndex()).shapes.add(a);
                listMode2.addElement(a.getName());
                jList2.setModel(listMode2);
            }
        }
        else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("square")){
            Square a = new Square();
            a.setName(layer.get(jList1.getSelectedIndex()).shapes.size()+" square");
            if(jList1.getSelectedIndex()<0) JOptionPane.showMessageDialog(rootPane, "bạn cần chọn layer");
            else {
                layer.get(jList1.getSelectedIndex()).shapes.add(a);
                listMode2.addElement(a.getName());
                jList2.setModel(listMode2);
            }
        }
        else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("triangle")){
            Triangle a = new Triangle();
            a.setName(layer.get(jList1.getSelectedIndex()).shapes.size()+" triangle");
            if(jList1.getSelectedIndex()<0) JOptionPane.showMessageDialog(rootPane, "bạn cần chọn layer");
            else {
                layer.get(jList1.getSelectedIndex()).shapes.add(a);
                listMode2.addElement(a.getName());
                jList2.setModel(listMode2);
            }
        }}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Layer a = new Layer();
        a.setName("layer "+layer.size());
        layer.add(a);
        listModel.addElement(a.getName());
        jList1.setModel(listModel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i =jList1.getSelectedIndex();
        if(i>=0){
        listModel.remove(i);
        layer.remove(i);
        jList1.setModel(listModel);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        listMode2.clear();
        for(int i =0;i < layer.get(jList1.getSelectedIndex()).shapes.size();i++){
            listMode2.addElement(layer.get(jList1.getSelectedIndex()).shapes.get(i).getName());
        }
        jList2.setModel(listMode2);
    }//GEN-LAST:event_jList1MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        if(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName().indexOf("cirle")>0){
              Graphics graphics = jPanel1.getGraphics();
              String s = layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getColer();
              if(s.equals("xanh dương"))graphics.setColor(Color.BLUE);
              else if(s.equals("xanh lá"))graphics.setColor(Color.GREEN);
              else if(s.equals("vàng"))graphics.setColor(Color.YELLOW);
              else if(s.equals("hồng"))graphics.setColor(Color.PINK);
              else graphics.setColor(Color.BLACK);
              int[] q={0,0,0,0,0,0};
               Cirle c = new Cirle();
               c = (Cirle) layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex());
              graphics.fillOval(c.getx(),
                      c.gety(),
                      c.getR(),
                      c.getR());
              jTextField4.setText(c.getx()+" "+c.gety());
              jTextField5.setText(c.getX()[0]+"");
              jTextField2.setText(c.getY()[0]+"");
        }
        if(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName().indexOf("hexagon")>0){
            Graphics graphics = jPanel1.getGraphics();
            String s = layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getColer();
              if(s.equals("xanh dương"))graphics.setColor(Color.BLUE);
              else if(s.equals("xanh lá"))graphics.setColor(Color.GREEN);
              else if(s.equals("vàng"))graphics.setColor(Color.YELLOW);
              else if(s.equals("hồng"))graphics.setColor(Color.PINK);
              else graphics.setColor(Color.BLACK);
              Hexagon h = new Hexagon();
              h = (Hexagon) layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex());
            graphics.fillPolygon(h.getX(), h.getY(), 6);
            jTextField4.setText(h.getx()+" "+h.gety());
            jTextField5.setText(h.getX()[0]+" "+h.getX()[1]+" "+h.getX()[2]+" "+h.getX()[3]+" "+h.getX()[4]+" "+h.getX()[5]);
              jTextField2.setText(h.getY()[0]+" "+h.getY()[1]+" "+h.getY()[2]+" "+h.getY()[3]+" "+h.getY()[4]+" "+h.getY()[5]);
        }
        if(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName().indexOf("rectangle")>0){
            Graphics graphics = jPanel1.getGraphics();
            String s = layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getColer();
              if(s.equals("xanh dương"))graphics.setColor(Color.BLUE);
              else if(s.equals("xanh lá"))graphics.setColor(Color.GREEN);
              else if(s.equals("vàng"))graphics.setColor(Color.YELLOW);
              else if(s.equals("hồng"))graphics.setColor(Color.PINK);
              else graphics.setColor(Color.BLACK);
            Rectangle r = new Rectangle();
            r = (Rectangle) layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex());
            r.timToaDo(r.getX(),r.getY(),r.getx() , r.gety());
            graphics.fillPolygon(r.getX(), r.getY(), 4);
            jTextField4.setText(r.getx()+" "+r.gety());
            jTextField5.setText(r.getX()[0]+" "+r.getX()[1]+" "+r.getX()[2]+" "+r.getX()[3]);
              jTextField2.setText(r.getY()[0]+" "+r.getY()[1]+" "+r.getY()[2]+" "+r.getY()[3]);
        }
        if(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName().indexOf("square")>0){
            Graphics graphics = jPanel1.getGraphics();
            String s1 = layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getColer();
              if(s1.equals("xanh dương"))graphics.setColor(Color.BLUE);
              else if(s1.equals("xanh lá"))graphics.setColor(Color.GREEN);
              else if(s1.equals("vàng"))graphics.setColor(Color.YELLOW);
              else if(s1.equals("hồng"))graphics.setColor(Color.PINK);
              else graphics.setColor(Color.BLACK);
            Square s = new Square();
            s = (Square) layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex());
            s.timToaDo(s.getX(),s.getY(),s.getx() , s.gety());
            graphics.fillPolygon(s.getX(), s.getY(), 4);
            jTextField4.setText(s.getx()+" "+s.gety());
            jTextField5.setText(s.getX()[0]+" "+s.getX()[1]+" "+s.getX()[2]+" "+s.getX()[3]);
              jTextField2.setText(s.getY()[0]+" "+s.getY()[1]+" "+s.getY()[2]+" "+s.getX()[3]);
        }
        if(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName().indexOf("triangle")>0){
            Graphics graphics = jPanel1.getGraphics();
            String s = layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getColer();
              if(s.equals("xanh dương"))graphics.setColor(Color.BLUE);
              else if(s.equals("xanh lá"))graphics.setColor(Color.GREEN);
              else if(s.equals("vàng"))graphics.setColor(Color.YELLOW);
              else if(s.equals("hồng"))graphics.setColor(Color.PINK);
              else graphics.setColor(Color.BLACK);
              Triangle t = new Triangle();
              t = (Triangle) layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex());
            graphics.fillPolygon(t.getX(), t.getY(),3 );
            jTextField4.setText(t.getx()+" "+t.gety());
            jTextField4.setText(t.getx()+" "+t.gety());
            jTextField5.setText(t.getX()[0]+" "+t.getX()[1]+" "+t.getX()[2]);
              jTextField2.setText(t.getY()[0]+" "+t.getY()[1]+" "+t.getY()[2]);
        }
        jTextField1.setText(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName());
    }//GEN-LAST:event_jList2MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).setColer(jComboBox2.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed

    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setText("");
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        jTextField5.setText("");
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

          String a;
          String[] b;
          int[] c = {0,0,0,0,0,0};
          int[] d = {0,0,0,0,0,0};
          a = jTextField4.getText();
          b = a.split(" ");
          layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).setx(Integer.parseInt(b[0]));
          layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).sety(Integer.parseInt(b[1]));
          a = jTextField5.getText();
          b = a.split(" ");
          int n = 0;
          if(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName().indexOf("rectangle")>0) n=2;
          if(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName().indexOf("square")>0) n=2;
          if(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName().indexOf("cirle")>0) n=2;
          if(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName().indexOf("hexagon")>0) n=6;
          if(layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).getName().indexOf("triangle")>0) n=3;
          for(int i=0;i<n;i++){
              c[i] = Integer.parseInt(b[i]);
          }
          a = jTextField2.getText();
          b = a.split(" ");
          for(int i=0;i<n;i++){
              d[i] = Integer.parseInt(b[i]);
          }
          layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).setX(c);
          layer.get(jList1.getSelectedIndex()).shapes.get(jList2.getSelectedIndex()).setY(d);
          jPanel1.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        for(int n=0;n<10;n++){
        for (int i=0;i<layer.get(jList1.getSelectedIndex()).shapes.size()-1;i++)
        {
            for (int j=i+1;j<layer.get(jList1.getSelectedIndex()).shapes.size();j++)
        {
            if(layer.get(jList1.getSelectedIndex()).shapes.get(i).getx()==layer.get(jList1.getSelectedIndex()).shapes.get(j).getx()&&
                    layer.get(jList1.getSelectedIndex()).shapes.get(i).gety()==layer.get(jList1.getSelectedIndex()).shapes.get(j).gety()){
                layer.get(jList1.getSelectedIndex()).shapes.remove(i);
                listMode2.remove(i);
                jList2.setModel(listMode2);
                System.out.println("tuan");
            }
        }
        }}
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    // End of variables declaration//GEN-END:variables
}
